global using System.Buffers;
global using System.Collections.Concurrent;
global using System.Diagnostics;
global using System.Globalization;
global using System.Net;
global using System.Net.Sockets;
global using System.Security.Cryptography;
global using System.Security.Cryptography.X509Certificates;
global using System.Text;
global using BlueHeighliner.Msmt;
global using BlueHeighliner.Msmt.Internal;
global using Microsoft.Extensions.DependencyInjection;
global using Moq;
global using Org.BouncyCastle.Crypto;
global using Xunit;
global using Certificate = Org.BouncyCastle.Tls.Certificate;
global using CertificateEntry = Org.BouncyCastle.Tls.CertificateEntry;
global using SignatureAlgorithm = Org.BouncyCastle.Tls.SignatureAlgorithm;
global using SignatureAndHashAlgorithm = Org.BouncyCastle.Tls.SignatureAndHashAlgorithm;
global using TlsUtilities = Org.BouncyCastle.Tls.TlsUtilities;
